// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYN9r7SU-T6z8HJx2Y-nlDA7wIuurgNNo',
    appId: '1:1038863431865:web:0b062d8e6b47141cb14368',
    messagingSenderId: '1038863431865',
    projectId: 'ecommerce-b1f7a',
    authDomain: 'ecommerce-b1f7a.firebaseapp.com',
    storageBucket: 'ecommerce-b1f7a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn-8tt4r1zYfYk2M8Rxdz2m3jgqMPwXHs',
    appId: '1:1038863431865:android:c49bebe244bb2098b14368',
    messagingSenderId: '1038863431865',
    projectId: 'ecommerce-b1f7a',
    storageBucket: 'ecommerce-b1f7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTkpg3swAZcsFe1q4nZQXZ8Ue35Nonbt0',
    appId: '1:1038863431865:ios:c0223864b1be406bb14368',
    messagingSenderId: '1038863431865',
    projectId: 'ecommerce-b1f7a',
    storageBucket: 'ecommerce-b1f7a.firebasestorage.app',
    androidClientId: '1038863431865-269bb8llpikjgpr4l3hdi1nst5kfq9sf.apps.googleusercontent.com',
    iosClientId: '1038863431865-a2q68k61l0m8ah7nsj91akdnm3f5v5mh.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTkpg3swAZcsFe1q4nZQXZ8Ue35Nonbt0',
    appId: '1:1038863431865:ios:c0223864b1be406bb14368',
    messagingSenderId: '1038863431865',
    projectId: 'ecommerce-b1f7a',
    storageBucket: 'ecommerce-b1f7a.firebasestorage.app',
    androidClientId: '1038863431865-269bb8llpikjgpr4l3hdi1nst5kfq9sf.apps.googleusercontent.com',
    iosClientId: '1038863431865-a2q68k61l0m8ah7nsj91akdnm3f5v5mh.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYN9r7SU-T6z8HJx2Y-nlDA7wIuurgNNo',
    appId: '1:1038863431865:web:05e8107be2dcc255b14368',
    messagingSenderId: '1038863431865',
    projectId: 'ecommerce-b1f7a',
    authDomain: 'ecommerce-b1f7a.firebaseapp.com',
    storageBucket: 'ecommerce-b1f7a.firebasestorage.app',
  );
}
